apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "bartek@smykla.com"
    privateKeySecretRef:
      name: letsencrypt-production
    http01: {}
    dns01:
      providers:
        - name: prod-digitalocean
          digitalocean:
            tokenSecretRef:
              name: do-dns-token
              key: access-token